name = "niji"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "niji-db"
database_id = "cdea7bec-ad06-42a8-b40e-72b4374a073e"
preview_database_id = "DB"

# [ai]
# binding = "AI"
