services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /workspace
    environment:
      - TZ=Asia/Tokyo
    command: sleep infinity
